### ISSUE TITLE
Docker Sandbox 404's

### ISSUE THREAD

**Issue by jharpster** [osmlab/atlas-checks#13]
The [link](https://github.com/osmlab/atlas-checks/blob/dev/docs/sandbox.md) to the Docker Sandbox 404's.

**Comment by matthieun** [comment]
Hi @jharpster. Can you double check the link? It can't be found by Github on my end.

**Comment by matthieun** [comment]
Oh it all makes sense here! The sandbox.md link in the doc is empty.

**Comment by jharpster** [comment]
It's definitely a 404 for me.

![image](https://user-images.githubusercontent.com/224853/33853676-9bae78c0-de73-11e7-8a10-ab837313c2f7.png)

**Comment by matthieun** [comment]
Yep. The link in the doc is what is missing. Had not realized from the title, sorry! We will get that sorted out.

**Comment by mgcuthbert** [comment]
I will clean up that documentation, this is errant documentation as there was never any docker sandbox developed and as such that section of the documentation should never have been included.

**Comment by mgcuthbert** [comment]
https://github.com/osmlab/atlas-checks/pull/17

**Comment by mgcuthbert** [comment]
I am closing this issue, as the documentation was updated in the PR above.
