### ISSUE TITLE
official docker image

### ISSUE THREAD

**Issue by stefanocudini** [osmlab/atlas-checks#289]
hi

just exists some official docker image for running in standalone way this tool?
I have only found references to continuous integration config realtive to docker..

**Comment by danielduhh** [comment]
Hey @stefanocudini, great idea. Using docker would help eliminate issues building the project with java11.

The Docker image requirements are...
- java 11 (openjdk/adoptjdk)
- gradle (we're at 6.3 now)

Here are some use cases I can see being helpful:
* Given a specified `ATLAS_CHECKS_VERSION` , download the maven shaded JAR and expose as an executable.
```shell
docker run -d —name=6.1.3 org.openstreetmap.atlas.checks.distributed.ShardedIntegrityCheckSparkJob  -input -countries... etc
```
* Bind your local workspace  (via mount or volume) to the container and execute the atlas checks gradle commands (run, build, shaded, etc.) 
```
docker run -d —name=6.1.3 docker run --mount type=bind,src=/path/to/repo,dst=/app/atlas-checks gradlew run -Pchecks.local.input=/path/to/data
```

Are there any additional cases you'd like covered?

**Comment by stefanocudini** [comment]
hi @daniel-j-h 

you know a similar java project with the same/similar dependencies..

whose exists a docker image to be used as a starting case

**Comment by danielduhh** [comment]
hey @stefanocudini , please review #294. I've added a Dockerfile using the [jdk11 docker-gradle](https://github.com/keeganwitt/docker-gradle/blob/master/jdk11/Dockerfile) image.

**Comment by stefanocudini** [comment]
hi @danielduhh 
thank you for your support

I can try to clone your fork and try it locally

how can I do a simple test to find out if it works after the build of the docker image?

**Comment by danielduhh** [comment]
After creating the docker image, you can execute the gradle run command:
```bash
docker run [image tag] run
```
If you want to store the outputs on your host machine:
```bash
docker run --mount type=bind,src=/path/to/host/atlas-checks,dst=/app/atlas-checks checks run
```
@stefanocudini

**Comment by stefanocudini** [comment]
what contains ```/app/atlas-checks``` data ors atlas-checks source?

**Comment by danielduhh** [comment]
@stefanocudini `/app/atlas-checks` is the location of the source code directory on the docker container
See: https://github.com/osmlab/atlas-checks/pull/294/files#diff-3254677a7917c6c01f55212f86c57fbfR4

**Comment by danielduhh** [comment]
Do you mind testing my PR? #13 @stefanocudini
