### ISSUE TITLE
InvalidTurnRestrictionCheck - update

### ISSUE THREAD

**Issue by lauracasiana** [osmlab/atlas-checks#290]
**Description**
Suggestion for adding some extra reasons to flag turn restrictions in the already existing InvalidTurnRestrictionCheck. 

**Requirements**
 Check Candidate for the extra steps:
 - Is a `Relation` that has already passed the original check

 Requirements to be flagged: 
 - if any of the members that are of Edge type do not have the **highway=*** tag, the object should be flagged. 
 - if any of the members that are of Edge type have the **oneway** tag but the restriction does not respect the direction, the object should be flagged. 
    Detailed steps: 
    - `from` member with **oneway=yes** and **firstNode='via'** or **oneway=-1** and **lastNode='via'**
    - `to` member with **oneway=yes** and **lastNode='via'** or **oneway=-1** and **firstNode='via'**

**Use Cases**

*Case 1: Bad oneway direction on member (France)*
 - in this case the **no_right_turn** should be implied since the `to` member has a **oneway=yes** tag. From [wiki](https://wiki.openstreetmap.org/wiki/Relation:restriction#Members) page: "There is no need to restrict turning into the wrong way of a one way street. This is taken for granted."
 -[https://www.openstreetmap.org/relation/1697422](https://www.openstreetmap.org/relation/1697422#map=17/46.12002/3.40488)
![image](https://user-images.githubusercontent.com/18010283/81054807-2860dd80-8ed0-11ea-903a-cbb674af1df8.png)

 - similar with the above example: [https://www.openstreetmap.org/relation/1697421](https://www.openstreetmap.org/relation/1697421#map=18/46.12105/3.40836)

*Case 2: Bad oneway direction on member (USA)*
- in this case the `from` member should not be possible since it is a oneway in the opposite direction. 
- [https://www.openstreetmap.org/relation/10997568](https://www.openstreetmap.org/relation/10997568)
![image](https://user-images.githubusercontent.com/18010283/81068419-0162d580-8ee9-11ea-9c27-1e0b69f1871a.png)
 
**Supported regions**
All countries

**What's not supported (optional):**

**References**
[https://wiki.openstreetmap.org/wiki](https://wiki.openstreetmap.org/wiki/Relation:restriction#Members)

**Comment by Bentleysb** [comment]
Thanks for the very clear description of your ideas. 
The use cases you give are already flagged by InvalidTurnRestricitonCheck. They are caught when trying to build a route through the network graph from the `from` member to the `to` member. However, it may be worth looking into providing better instructions for these cases, as it may be difficult for editors to identify the problem in some cases. 
I am also not sure how well atlas handles reverse one way tagging. It would be worth checking how features tagged with `one_way=-1` or `one_way=reversed` are imported into an atlas.

**Comment by lauracasiana** [comment]
Closing the issue since it is already covered.

**Comment by sayas01** [comment]
All the use cases mentioned are taken care in the existing InvalidTurnRestrictionCheck. Having clear instructions for various cases would be a good improvement to the check. InvalidTurnRestrictionCheck is being revisited to add clear instructions.
