### ISSUE TITLE
Bad tags (osmose 3050, 3150, and 4090)

### ISSUE THREAD

**Issue by tsmock** [osmlab/atlas-checks#352]
**Description**
Check for bad tags, tags that have a typo, and unwanted tags.

For unwanted tags, the tag should exist in [OSM Wiki Data](https://wiki.openstreetmap.org/wiki/Data_items) (e.g., https://wiki.openstreetmap.org/w/api.php?action=wbgetentities&sites=wiki&titles=Key:lanes&languages=en&format=json -- human readable [here](https://wiki.openstreetmap.org/wiki/Item:Q372)). This also affects tags that have a typo (if the key indicates that it has well-known values (example: [Key:bridge:movable](https://wiki.openstreetmap.org/wiki/Item:Q104)), if there is not a wiki item for that value, then more work must be done). This requirement is due to the [Meta](https://wiki.openstreetmap.org/wiki/Data_items#Meta_item) information that each key can have (`de facto`, `in use`, `approved`, `rejected`, `voting`, `draft`, `abandoned`, `proposed`, `obsolete`, `deprecated`, `discardable`, and `imported`). `discardable` and `rejected` are definitely unwanted, while `obsolete` and `deprecated` should be used to indicate that there is a newer tagging method to the user.

**Requirements**
1. Check Candidate
- Has tags
- Is not already flagged by an existing bad tag/key/value check (this may be difficult to do, see `ConditionalRestrictionCheck`, a utility class/parent class may be necessary to register keys that have _specific_ checks, but probably calling `validCheckForObject` will be good enough).

**Use Cases**
This section summarizes the various use cases for this check and provides potential enhancement suggestions if needed. The uses cases should act as a test in a way, such that when the analysis/enhancement is completed, these types of use cases should be found or eliminated.

For each use case, please add a screenshot of the feature & openstreetmap.org link (or other sources). If necessary, edit the screenshot to better illustrate the use case.

Example:

*Case 1: Invalid Highway Tag ([Togo](https://www.openstreetmap.org/node/5343281075))*
 - `highway=Station de carburant pour voiture` should be flagged (and should already be flagged). This check is primarily for instances where hardcoded values are not available (as it is with `highway`).
 - https://www.openstreetmap.org/node/5343281075
![Station de carburant pour voiture](https://user-images.githubusercontent.com/45215054/91472002-11197780-e854-11ea-982f-b870f0676675.png)

**Further investigation**
It is expected that there will be false positives where a proposal has recently been accepted, but a Wiki Data item has not been created. An additional script should be provided to parse the json for items that may need to be added to the wiki (automatically done for keys by [bot](https://wiki.openstreetmap.org/wiki/Data_items#Item_creation_process) when a tag matches a regex AND there are more than 10 instances).

**Supported regions**
All countries

**What's not supported (optional):**
Autocorrections -- this may be possible with the addition of Levenshtein distance calculations, when there is expected to be a well-known value (so names need not apply).

**Intended methodology:**
* `InvalidTagsCheck` will be modified to check the key and value of an object if it is not flagged already (the assumption being that the specific flags are more accurate than those on the wiki)
* If a local TagInfo database exists, query the database for the key and value incidence. Record this to a variable.
* For each key, get the appropriate wiki data item (preferably from a data dump, _not_ the live server, a utility script similar to [this](https://github.com/Sophox/sophox/blob/metabot/metabot/metabot/DataItems.py#L29) should be written).
  * If the key has the `well-known` values classification, check that the tag page exists. Else if there is a `regex`, check the value against the regex. Else continue on.
  * If the key has a `status` of `discardable`, `rejected`, `abandoned`, or `imported` (`imported` is a maybe), flag for removal.
  * If the key does not exist in wiki data, and the key is over a specific (configurable?) threshold, write instructions for a wiki editor
  * If the key does not exist in wiki data, and the key is under a specific (configurable?) threshold, write instructions for modification/removal
  * If the key is over a specific (configurable?) threshold, is _not_ `well-known`, flag for a wiki editor to add a regex expression checker for (so a `name` tag could be expected to match `.*`).
  * If the key is prohibited on the current element (node/way/area/relation), add instructions to that effect
* A script must be written to remove and consolidate instructions for wiki editors, to separate those from those that should be fixed.

**References**
* [OSM Data Items](https://wiki.openstreetmap.org/wiki/Data_items)
* [OSM Wiki Dump](https://wiki.openstreetmap.org/dump/) (either this, making lots of network calls)
* [Value Validation Regex](https://wiki.openstreetmap.org/wiki/Property:P13) ([example](https://wiki.openstreetmap.org/wiki/Item:Q574))
* [TagInfo Usage Database](https://taginfo.openstreetmap.org/download)
* [Deprecated Tags](https://wiki.openstreetmap.org/wiki/Deprecated_features)
* [Tagwatch Cleaner](https://wiki.openstreetmap.org/wiki/User:FrViPofm/TagwatchCleaner)

**Comment by dcastrowa** [comment]
Utilizing InvalidTagsCheck will definitely be the best approach to this issue. I do see some complications happening due to the complexity of the requirements for this issue it look like there is enough references and tools out there to make this happen. I do also see that there may be a lot of false positives which may end up making this check invalid.

**Comment by tsmock** [comment]
I do foresee a lot of (initial) false positives. Most of the time, the FP can be fixed in the OSM Wiki Data (in #357 I'm setting a threshold for "probably an error" and "probably needs to be documented" in order to alleviate the issue _and_ improve documentation). My intent is to split out all issues that specifically refer to adding to the wiki and condensing them so that human editors can look at them and document them. But this does depend upon the wiki data being "right".

All that being said, there are enough `created_by` tags that shouldn't exist that I'm going to be surprised if I don't have 90% TP (actually, in my limited testing thus far, I haven't seen that many FP). The biggest FP from my last run is largely due to some tags not fully documented (specifically, the ones that stood out the most were for `border_type=eez`, if only due to the size).

And yes, it is a complex check. I'll have to rebase the branch I was working on to `dev`, since some other people made some modifications to InvalidTagsCheck (which I don't mind -- this has been taking me longer than expected since I had to go down some rabbit holes, like making modifications for external data, making some modifications so that external data doesn't leak and bring about an OOM, etc.).

For the record, #357 depends upon #398, which in turn depends upon osmlab/atlas-generator#167.

**Comment by dcastrowa** [comment]
Great! It sounds like there is a solution and some known issues with the initial false positives. I think this is achievable with the given status.
