### ISSUE TITLE
[Feature Request] Create FeatureChange and ChangeDescription deserializers 

### ISSUE THREAD

**Issue by danielduhh** [osmlab/atlas-checks#364]
**Is your feature request related to a problem? Please describe.**

- Create FeatureChange & ChangeDescription deserializer.

This deserializer will read CheckFlag GeoJSON outputs and convert the fix suggestions in the [ChangeDescription](https://github.com/osmlab/atlas/blob/dev/src/main/java/org/openstreetmap/atlas/geography/atlas/change/description/ChangeDescription.java) model. This will allow us to leverage all that comes with the FeatureChange and ChangeDescription classes

**Comment by Bentleysb** [comment]
Complete
