### ISSUE TITLE
[Feature Request] Add Cooperative Challenges to MapRouletteUploadCommand

### ISSUE THREAD

**Issue by danielduhh** [osmlab/atlas-checks#365]
**Is your feature request related to a problem? Please describe.**

- Update the MapRouletteUpload command to convert auto-fix suggestions into [Cooperative Challenges ](https://github.com/osmlab/maproulette3/wiki/Cooperative-Challenges)

Cooperative challenges bring in-progress work to a MapRoulette task for completion or verification. Tag changes can be committed directly to OSM from within MapRoulette. 

Supported operations: create, modify, delete tags 
```json
{
	"cooperativeWork": {
		"meta": {
			"version": 2,
			"type": 1
		},
		"operations": [{
			"operationType": "modifyElement",
			"data": {
				"id": "way/792729120",
				"operations": [{
					"operation": "unSetTag"
				}]
			}
		}]
	}
}
```

**Comment by seancoulter** [comment]
Tag auto fixes addressed in https://github.com/osmlab/atlas-checks/pull/411

**Comment by Bentleysb** [comment]
complete
