### ISSUE TITLE
Highway inconsistency check - InvalidTagsCheck

### ISSUE THREAD

**Issue by mm-ciub** [osmlab/atlas-checks#377]
**Description**
Extension of the InvalidTagsCheck to look for missing tags in certain tag combinations containing or requiring `highway` tags, like junction or oneway.

**Requirements**
1. Check Candidate (example)
- is `Edge`| `Node`
- matched a specific TaggableFilter provided for each case

**Use Cases**
1. `highway` tag missing on a `junction` ( junction->*&highway->! )
https://www.openstreetmap.org/way/802707014
<img width="310" alt="image" src="https://user-images.githubusercontent.com/68378600/94828244-f10c4380-0411-11eb-9121-1fbb6a548a1e.png">

2. `highway` tag missing on `oneway` ( oneway->*&highway->! )
https://www.openstreetmap.org/way/823990367
<img width="318" alt="image" src="https://user-images.githubusercontent.com/68378600/94827478-295f5200-0411-11eb-953b-7d85e159c101.png">

3. `highway` tag missing on `tracktype ` ( tracktype->*&highway->!&leisure->!track )
https://www.openstreetmap.org/way/300713929
<img width="312" alt="image" src="https://user-images.githubusercontent.com/68378600/94829018-c40c6080-0412-11eb-8bca-c91651eae9e0.png">

4. `ref` tag missing one `emergency access point`

5. `highway` missing `footway`, `path` or `construction` for `footway=sidewalk`

https://www.openstreetmap.org/way/29408268

<img width="308" alt="image" src="https://user-images.githubusercontent.com/68378600/94820355-0d57b280-0409-11eb-9bb5-e564b32ea81e.png">

6. Motorway without ‘ref’, ‘nat_ref’, ‘int_ref’, ‘noref’ tag 
https://www.openstreetmap.org/way/674134910
<img width="310" alt="image" src="https://user-images.githubusercontent.com/68378600/94828812-86a7d300-0412-11eb-9f7b-1e6ff278fde2.png">

**Further investigation**
-

**Supported regions**
All countries

**What's not supported (optional):**
-

**References**
Junction tag usage: https://wiki.openstreetmap.org/wiki/Key:junction
Oneway tag usage: https://wiki.openstreetmap.org/wiki/Key:oneway
Emergency access point: https://wiki.openstreetmap.org/wiki/Tag:highway%3Demergency_access_point
Tracktype tag usage: https://wiki.openstreetmap.org/wiki/Key:tracktype
Footway tag usage: https://wiki.openstreetmap.org/wiki/Key:footway

**Comment by Bentleysb** [comment]
@mm-ciub, is this complete?

**Comment by mm-ciub** [comment]
yes, it is. It got merged with PR #397
