### ISSUE TITLE
[Fix Suggestions] Areas With Highway Tag Check

### ISSUE THREAD

**Issue by ylinzhi** [osmlab/atlas-checks#386]
**Which Atlas check is the fix suggestion related to?** 

AreasWithHighwayTagCheck
Description: https://github.com/osmlab/atlas-checks/blob/dev/docs/checks/areasWithHighwayTagCheck.md
Script: https://github.com/osmlab/atlas-checks/blob/dev/src/main/java/org/openstreetmap/atlas/checks/validation/areas/AreasWithHighwayTagCheck.java

**Describe more details of suggested fix(es)**

*Suggested Fix 1*: 

- Type for fixing: Tag fix

- Operation: Delete

- Suggested Action: Remove `area=yes` tag on the flagged feature(s)

**Is there any code enhancement needed if adding the fix suggestion component?**

Yes

* When the flagged feature is a relation, the suggested fix shouldn't be applied

**Comment by atiannicelli** [comment]
I believe we can close this as complete as this PR (https://github.com/osmlab/atlas-checks/pull/361) added suggestions for this check.

**Comment by seancoulter** [comment]
@ylinzhi the check only considers Atlas edges and areas, but may still suggest tag removes from edges/areas that are in relations (https://github.com/osmlab/atlas-checks/pull/361). If this is a problem let me know, otherwise we can close this out

**Comment by Bentleysb** [comment]
Closing, as there has been no action in several months and this appears to be completed by https://github.com/osmlab/atlas-checks/pull/361.
