### ISSUE TITLE
[Fix Suggestions] Road Name Gap Check

### ISSUE THREAD

**Issue by ylinzhi** [osmlab/atlas-checks#390]
**Which Atlas check is the fix suggestion related to?** 

Road Name Gap Check
Description: https://github.com/osmlab/atlas-checks/blob/dev/docs/checks/RoadNameGapCheck.md
Script: https://github.com/osmlab/atlas-checks/blob/dev/src/main/java/org/openstreetmap/atlas/checks/validation/tag/RoadNameGapCheck.java

**Describe more details of suggested fix(es)**

*Suggested Fix 1*: 

- Type of fixing: Tag fix

- Operation: Add or Modify

- Suggested Action: 1) **Add** proper road segment name tag when it's missing. 2) **Modify** proper road segment name tag when it's inconsistent with its connected road segments

**Is there any code enhancement needed if adding the fix suggestion component?**

No

**Comment by sayas01** [comment]
👍

**Comment by mm-ciub** [comment]
Is this still open? I would be interested to work on it.

**Comment by atiannicelli** [comment]
As far as I know it is. The road name gap check does not have auto fix suggestions yet. go for it!

**Comment by mm-ciub** [comment]
I believe this issue could be closed now.

**Comment by Bentleysb** [comment]
complete
