### ISSUE TITLE
[Fix Suggestions] Mixed Case Name Check 

### ISSUE THREAD

**Issue by ylinzhi** [osmlab/atlas-checks#393]
**Which Atlas check is the fix suggestion related to?** 

MixedCaseNameCheck
Description: https://github.com/osmlab/atlas-checks/blob/dev/docs/checks/mixedCaseNameCheck.md
Script: https://github.com/osmlab/atlas-checks/blob/main/src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/OverlappingEdgeCheck.java

**Describe more details of suggested fix(es)**

*Suggested Fix 1*: 

- Type of fixing: Tag fix

- Operation: Modify

- Suggested Action: Modify name(s) to appropriate case

- Restriction: Fix should align with languages in selected countries

**Is there any code enhancement needed if adding the fix suggestion component?**

No

**Comment by sayas01** [comment]
👍

**Comment by vladlemberg** [comment]
@sayas01, could you please assign this task to me ?
