### ISSUE TITLE
[Fix Suggestions] Highway To Ferry Tag Check 

### ISSUE THREAD

**Issue by ylinzhi** [osmlab/atlas-checks#396]
**Which Atlas check is the fix suggestion related to?** 

Highway To Ferry Tag Check
Description: https://github.com/osmlab/atlas-checks/blob/6c987dd8bb0e87df4900e9a7a605f6a13ecfce7d/docs/checks/highwayToFerryTagCheck.md
Script: https://github.com/osmlab/atlas-checks/blob/6c987dd8bb0e87df4900e9a7a605f6a13ecfce7d/src/main/java/org/openstreetmap/atlas/checks/validation/tag/HighwayToFerryTagCheck.java

**Describe more details of suggested fix(es)**

*Suggested Fix 1*: 

- Type of fixing: Tag fix

- Operation: Modify

- Suggested Action: Change the `highway=*` tag to `ferry=*` tag that aligns with the classification of connected highways

**Is there any code enhancement needed if adding the fix suggestion component?**

No

**Comment by Bentleysb** [comment]
👍

**Comment by mm-ciub** [comment]
I believe this issue can be closed now.

**Comment by Bentleysb** [comment]
Complete
