### ISSUE TITLE
RoundaboutMissingTagCheck v2 

### ISSUE THREAD

**Issue by vladlemberg** [osmlab/atlas-checks#399]
**Describe the bug**
Improve check output by implementing following logic: 

1. Remove [Turning loops](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dturning_loop), [Turning Circles](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dturning_circle).
2. Remove navigable ways with motor_vehicle=no
3. Remove navigable ways with foot=yes
4. Remove navigable ways with footway tag
5. Remove navigable ways with construction tag 

**To Reproduce**
Turning Circle: [example](https://www.openstreetmap.org/way/708115016)
Turning Circle: [example2](https://www.openstreetmap.org/way/271162784)
Navigable but motor_vehicle=no: [example](https://www.openstreetmap.org/way/263363745)
Navigable with foot=yes: [example](https://www.openstreetmap.org/way/266867982)
Navigable with footway tag: [example](https://www.openstreetmap.org/way/570478109)
Navigable with construction tag: [example](https://www.openstreetmap.org/way/363403197)
Navigable with access=private: [example](https://www.openstreetmap.org/way/631176898)

**Expected behavior**
All above cases should be extracted from the RoundaboutMissingTagCheck

**Comment by atiannicelli** [comment]
Complete. @vladlemberg can you close this issue?

**Comment by vladlemberg** [comment]
merger to dev.
