### ISSUE TITLE
[Fix Suggestions] Water Way Check

### ISSUE THREAD

**Issue by atiannicelli** [osmlab/atlas-checks#403]
**Water Way Check**
Description: https://github.com/tsmock/atlas-checks/blob/dev/docs/checks/waterWayChecks.md
Code: https://github.com/osmlab/atlas-checks/blob/dev/src/main/java/org/openstreetmap/atlas/checks/validation/areas/WaterAreaCheck.java

**Describe more details of suggested fix(es)**

Suggested Fix 1:
  Type of fixing: Way fix
  Operation: Modify
  Suggested Action: reverse the way direction 

**Is there any code enhancement needed if adding the fix suggestion component?**

No

**Comment by Bentleysb** [comment]
👍

**Comment by atiannicelli** [comment]
Please assign this to @tsmock
