### ISSUE TITLE
[Fix Suggestions] Single Segment Motorway Check

### ISSUE THREAD

**Issue by sayas01** [osmlab/atlas-checks#407]
**Which Atlas check is the fix suggestion related to?** 

**SingleSegmentMotorwayCheck:**
Description: https://github.com/osmlab/atlas-checks/blob/dev/docs/checks/singleSegmentMotorwayCheck.md

Source Code: https://github.com/osmlab/atlas-checks/blob/dev/src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/SingleSegmentMotorwayCheck.java

**Describe more details of suggested fix(es)**

*Suggested Fix 1*: 

- Type: Tag

- Operation: Modify

- Action: Update the highway tag of single segment motorway to the highway type of connected edges.

**Is there any code enhancement needed if adding the fix suggestion component?**

Yes, this requires code changes to fetch the highway tag of connected edges and determine which highway tag of connected edges to be assigned to the single segment motorway. 

If yes, provide details about what and where the enhancement is needed.  Ex. the fix requires excluding checks on relation

**Comment by mm-ciub** [comment]
I believe this issue can be closed.
