### ISSUE TITLE
[Fix Suggestions] Intersecting Buildings Check

### ISSUE THREAD

**Issue by sayas01** [osmlab/atlas-checks#408]
**Which Atlas check is the fix suggestion related to?** 

**IntersectingBuildingsCheck:**
Description: https://github.com/osmlab/atlas-checks/blob/dev/docs/checks/intersectingBuildingsCheck.md

Source Code: https://github.com/osmlab/atlas-checks/blob/dev/src/main/java/org/openstreetmap/atlas/checks/validation/intersections/IntersectingBuildingsCheck.java

**Describe more details of suggested fix(es)**

*Suggested Fix 1*: 

- Type: Geometry

- Operation: Delete

- Action:  Delete one of the buildings that are equal/ fully contained by another building.
The check flags three case:
1) buildings intersecting one another
2) buildings overlapping one another
3) buildings that are equal.

Autofix action will be to delete one of the buildings among the two overlapping buildings, that belongs to (2) and (3) cases.

**Is there any code enhancement needed if adding the fix suggestion component?**

No, the three cases are already flagged individually.

**Comment by brianjor** [comment]
I've started working on this one.
