### ISSUE TITLE
TollValidationCheck

### ISSUE THREAD

**Issue by reichg** [osmlab/atlas-checks#412]
## ***TollEscapeCheck - Requirements***

Developers: Gabe Reichenberger 
Date: 10/09/2020 

### ***Description*** 

 This check attempts identify 3 cases to validate toll tag modeling.

### ***Requirements***  
***An Atlas Object must meet the following criteria to be considered***

Atlas Object
- Is an Edge 
- Is car navigable 
- Is not private access  
- Minimum tertiary classification

### ***Cases***
***Case 1 - Way intersects toll feature and needs toll=yes tag added to it.***
- Check if way contains node with toll feature related tags or intersects a an area with toll related tags. (examples: barrier=toll_booth and highway=toll_gantry)

***Case 2 - Way is completely surrounded by toll=yes tags and needs toll=yes tag added to it.***
- Check if every connected way has toll=yes tag, flag if true.

***Case 3 - Way does not require a toll because there is a possible route that avoids paying a toll.***
- Checks if there are upstream AND downstream routes that avoid a toll. 
- This is a more complicated case and typically requires investigation on the way in question and edges proving escapable to see if there is a modeling issue.

### ***Live Examples***
***Case 1***
[Way:712334447](https://www.openstreetmap.org/way/712334447) intersects toll feature (Start node is a toll feature)

![image](https://user-images.githubusercontent.com/18335251/110234992-5e9d2e00-7ee2-11eb-952a-00aa668a71b2.png)

***Case 2***
***Case 3***
 
### ***Supported Countries***
All

**Comment by Bentleysb** [comment]
@reichg, is this full resolved by https://github.com/osmlab/atlas-checks/pull/432?

**Comment by reichg** [comment]
Yes, sorry!

**Comment by atiannicelli** [comment]
Can we close this please.

**Comment by reichg** [comment]
> Can we close this please.

linked PR for the update to this check. Will close when PR is complete.
