### ISSUE TITLE
[New Check]SourceMaxSpeedCheck 

### ISSUE THREAD

**Issue by mm-ciub** [osmlab/atlas-checks#413]
**Description**
This check should verify that the `source:maxspeed` tag is following the rules established here: https://wiki.openstreetmap.org/wiki/Key:source:maxspeed
The possible values:
- sign (where the speed limit is defined by a numeric sign.)
- markings (where the speed limit is defined by painted road markings.)
- <country_code>:\<context\> (where the speed limit is defined by a particular context, for example urban/rural/motorway/etc., and no maxspeed is signposted)

**Requirements**
1. Check Candidate 
 - Is an `Edge`|`Point`
 - Has `source:maxspeed` tag

**Use Cases**

*Case 1: Not following country:context rule (USA)*
 - `source:maxspeed=Unless otherwise posted speed limit 25 MPH in Oklahoma City;OKC code § 32-166.`
Should have been US:25
 - https://www.openstreetmap.org/way/858591689

*Case 2: URL as value (UY)*
- `source:maxspeed=http://monolitos.montevideo.gub.uy/resoluci.nsf/WEB/Numero/954-13` (10 774 cases)
- https://www.openstreetmap.org/way/78113805#map=15/-34.8557/-56.3414

*Case 3: incorrect value based on survey (USA)*
- `source:maxspeed=survey 2014-05-17`(257 cases)
- https://www.openstreetmap.org/way/9140656

**Further investigation**
Variations of `zone` as values are accepted as exceptions.

**Supported regions**
There are some exceptions that need to be taken into account: 
- UK uses `maxspeed:type=* ` for the purpose associated with `source:maxspeed`
- Belgium has relevant regions source:maxspeed=BE-VLG:..., source:maxspeed=BE-WAL:... and source:maxspeed=BE-BRU

**What's not supported (optional):**
This section explains what elements are not supported by this check, whether or not these elements should be included/addressed in the future, and if these cases are better handled in another (existing or new) check.

**References**
Official OSM wiki documentation:
https://wiki.openstreetmap.org/wiki/Key:source:maxspeed
Cases found using tag info: https://taginfo.openstreetmap.org/keys/source%3Amaxspeed

**Comment by Bentleysb** [comment]
This looks good as a new check. The only question I have is if you have looked into examples of source:maxspeed tags on nodes. I see from the wiki that this tag can appear on OSM nodes. It would be worth checking some examples in an Atlas to see if those cases always become atlas nodes, or if some of them become points. My guess would be that they are more likely to become points (also many OSM nodes become both atlas nodes and points).

**Comment by mm-ciub** [comment]
So I looked over the node cases and from taginfo, there seem to be 10 692 cases of this tag to be present on nodes.
Some examples of these nodes:
https://www.openstreetmap.org/node/68466222#map=19/33.80409/-84.63726
https://www.openstreetmap.org/node/5121078122 - this one is not part of a way
- there seem to be a lot of cases in Europe:
https://www.openstreetmap.org/node/5312712494
https://www.openstreetmap.org/node/3903264973
Perhaps it might be safer to look into both node and point then?

**Comment by Bentleysb** [comment]
Looking at these examples of osm nodes with this tag, it is clear that many of them will not be atlas nodes. All of them will be atlas points simply because they have an osm tag (we know they will have source:maxspeed). So it looks like this check should look at Edges and Points. 

Everything else about this looks good.

**Comment by mm-ciub** [comment]
I updated the issue accordingly. Thank you very much for the help.

**Comment by mm-ciub** [comment]
This issue can be closed.
