### ISSUE TITLE
[Fix Suggestions] Roundabout Missing Tag Check

### ISSUE THREAD

**Issue by atiannicelli** [osmlab/atlas-checks#416]
**Which Atlas check is the fix suggestion related to?** 

**RoundaboutMissingTagCheck:**
https://github.com/osmlab/atlas-checks/blob/dev/docs/checks/roundaboutMissingTagCheck.md

source Code: 
https://github.com/osmlab/atlas-checks/blob/dev/src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/RoundaboutMissingTagCheck.java

**Describe more details of suggested fix(es)**

*Suggested Fix 1*: 

- Type: Tag. 

- Operation: Add

- Action: Add tag "junction=roundabout" to flagged features

**Is there any code enhancement needed if adding the fix suggestion component?**

No

**Comment by atiannicelli** [comment]
Please assign to @vladlemberg

**Comment by Bentleysb** [comment]
👍

**Comment by atiannicelli** [comment]
This autofix has been completed.
