### ISSUE TITLE
[Bug] Atlas 6.3.3 breaks InvalidMultiPolygonRelationCheckTest

### ISSUE THREAD

**Issue by tsmock** [osmlab/atlas-checks#427]
**Describe the bug**
Specific tests broken:
* testOpenRelation (expected: `"The Multipolygon relation 39569 with members : [39766, 39565] is not closed at some locations : [POINT (103.9145902 1.4119302), POINT (103.9462109 1.4263886), POINT (103.9462109 1.4263886), POINT (103.9256395 1.4483904)]"`, actual: `"The Multipolygon relation 39569 with members : [39766, 39565] is not closed at some locations : [POINT (103.9145902 1.4119302), POINT (103.9256395 1.4483904)]"`)
* testOpenPolygon (expected: `"The Multipolygon relation 0 with members : [0] is not closed at some locations : [POINT (-71.6970306 18.4360737), POINT (-71.7052283 18.4273807), POINT (-71.7194204 18.4360044), POINT (-71.6970306 18.4360737)]"`, actual: `"The Multipolygon relation 0 with members : [0] is not closed at some locations : [POINT (-71.7194204 18.4360044), POINT (-71.7052283 18.4273807)]"`)

**To Reproduce**
1. Update atlas dependency to 6.3.3

**Expected behavior**
No failing tests

**Extra Information**
https://github.com/osmlab/atlas/commit/c60504d3bf805ed9de5fea1d44d3f06add5fd89b is the breaking commit.
It _may_ be more appropriate to file this against atlas.

**Comment by Bentleysb** [comment]
I just updated those test recently to reflect a change in atlas logic. It looks like the new logic is now disabled by default. I will look into this. 
@tsmock is there something you need in atlas 6.3.3?

**Comment by tsmock** [comment]
Nope. I had been building `atlas-generator` and `atlas-checks` at the same time for https://github.com/osmlab/atlas-generator/pull/167 (a requirement for #398 , which is a requirement for #352 ), and `atlas-generator` just updated to atlas 6.3.3.

So I don't _need_ atlas 6.3.3 in atlas-checks, it just happens to be a dependency of atlas-generator, and I figured we would eventually need to update the atlas dependency.
