### ISSUE TITLE
OpenBoundaryCheck

### ISSUE THREAD

**Issue by reichg** [osmlab/atlas-checks#439]
### Description
This check attempts to check for Administrative relations that should be closed polygons but are not. 

##### Check Candidate
 - Must be a Relation
 - Must be of type Boundary
 - Must have admin_level tag

##### True Positives
 - [Yakıntaş](https://www.openstreetmap.org/relation/8284136) neighborhood boundary is not closed

##### False Positives
 - [Seattle](https://www.openstreetmap.org/relation/237385) city is a closed boundary 

**References**
[Osmose Issue](https://wiki.openstreetmap.org/wiki/Osmose/issues#6010)
[Osmose Analyzer](https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_relation_open.py)

**Comment by Bentleysb** [comment]
Just noting here that this will suffer from the know large relation issue in the sharded checks job. Handling of this has been discussed offline and this otherwise looks good to go.
