### ISSUE TITLE
ConcerningAngleBuildingCheck

### ISSUE THREAD

**Issue by reichg** [osmlab/atlas-checks#450]
**Description**
This check attempts to flag buildings who have angles between 80 and 89.9 degrees. (Acute)

**Requirements**
* Check Candidate:
  1. Is an area or relation AND is a building or is part of a building.
  2.  Angles between consecutive segments cannot be between 80 - 89.7 degrees or between 90.3 - 100 degrees.

**Use Cases**
Example:
[Building: 791199451](https://www.openstreetmap.org/way/791199451) fits the requirements and has angles that need to be squared.

**Supported regions**
All

**Comment by Bentleysb** [comment]
I am curious about the use cases this will be trying to capture. We already have [SpikyBuildingCheck](https://github.com/osmlab/atlas-checks/blob/dev/docs/checks/spikyBuildingCheck.md) which flags very acute angles, but this seems to be more for angles that have not been properly squared. 
I am a bit concerned about the number of false positives that there may be. This may take a bit of tuning to work those out. I would suggest making the threshold for the flagged angles configurable.

**Comment by reichg** [comment]
Yeah, I was looking at the SpikyBuildingCheck and was thinking maybe it could be tied into that. The only problem is for organizational and metric purposes it makes sense to keep them separate. I've already done one pass through this check and got over 50k flags. Definitely need to tune this properly to remove complex buildings and buildings with curves I think. > I am curious about the use cases this will be trying to capture. We already have [SpikyBuildingCheck](https://github.com/osmlab/atlas-checks/blob/dev/docs/checks/spikyBuildingCheck.md) which flags very acute angles, but this seems to be more for angles that have not been properly squared. 
> 
> I am a bit concerned about the number of false positives that there may be. This may take a bit of tuning to work those out. I would suggest making the threshold for the flagged angles configurable.
