### ISSUE TITLE
[Improvement] MalformedRoundaboutCheck: Minimum OSM Nodes/Angles

### ISSUE THREAD

**Issue by brianjor** [osmlab/atlas-checks#459]
**Description**
Checks amount of OSM nodes in roundabout are at or above a certain number.
This is a request from our editors to flag roundabouts that are made of fewer than 9 OSM nodes.
We are also checking the angle between the segments of the roundabout.

**Requirements**
This improvement will add a check for the number of OSM nodes that make up the roundabout.
It will also check that the angle between the roundabout segments is not between 10° and 40°.
Same requirements as are currently set in MalformedRoundaboutCheck

**Use Cases**
TP
This roundabout has fewer than 9 OSM nodes
https://www.openstreetmap.org/way/8035973
![image](https://user-images.githubusercontent.com/22751140/103686185-48efa480-4f43-11eb-93ac-8cc249096c17.png)

**Supported regions**
All countries.

**Comment by Bentleysb** [comment]
@brianjor, just to check, you mean OSM nodes here not Atlas nodes, right?

**Comment by brianjor** [comment]
@Bentleysb, yes, OSM nodes.

**Comment by vladlemberg** [comment]
@brianjor, is it new integrity check ?  please also provide use cases with OSM ids and your candidate criteria. 

if you are trying to flag all roundabouts that are not "round shaped", i'd recommend calculating a degree between each node. 

there a quite a bit of roundabouts with more than 9 shape point that looks not circular at all. 

I'm also currently working in this check. plan to finish today/tomorrow +-

**Comment by brianjor** [comment]
@vladlemberg, this is not a new check. It is just adding a new flag to the check.
The addition is only looking at the count of OSM nodes that make up the roundabout, not the shape.

**Comment by vladlemberg** [comment]
@brianjor what would be the editing action after you flag it ?

**Comment by brianjor** [comment]
@vladlemberg More nodes would need to be added to the roundabout.

**Comment by vladlemberg** [comment]
@brianjor, to make it more "round shaped" ? if yes, then your logic will flag only certain percent of malformed roundabouts. let's say one of the edges in your example has few more extra shape points, then it wont be flagged. 

to make it more scalable i'd recommend calculating angle between each node utilizing "anglesGreaterThanOrEqualTo" and "anglesLessThanOrEqualTo" methods in org.openstreetmap.atlas.geography.PolyLine

if angle between any nodes:   10%  < angle > 40%  - your candidate.

**Comment by brianjor** [comment]
@vladlemberg I talked with our editors, they agree that checking the angles would be a good addition. I'll add it to the requirements.

**Comment by vladlemberg** [comment]
@brianjor, that's cool! I also submitted Autofix PR for MalformedRoundabout check. Not sure if its going to affect your development. https://github.com/osmlab/atlas-checks/pull/449/

**Comment by brianjor** [comment]
@vladlemberg Just took a peek at your PR, doesn't look like it will be an issue. I'll just wait for yours to be merged before starting my PR.

**Comment by vladlemberg** [comment]
@brianjor, #449 got merged.
