### ISSUE TITLE
[Check Improvement] EdgeCrossingEdgeCheck improvement

### ISSUE THREAD

**Issue by vladlemberg** [osmlab/atlas-checks#466]
EdgeCrossingEdgeCheck is only working with Car Navigable Highway Types and not checking layer (z-level) if crossing edge is a bridge. 

To improve:
1) Add configurable value: highway_type [vehicle_only|pedestrian_only] to configuration.json.
2) If both crossing candidates don't have level tag, check if one of the candidate is a bridge (default level=1)

True Positive (Case 1):
![image](https://user-images.githubusercontent.com/62575608/104067633-5cf00c00-51b8-11eb-894f-93dd82eeca4e.png)

True Positive (Case 1):
![image](https://user-images.githubusercontent.com/62575608/104067685-77c28080-51b8-11eb-8e5f-afb7bcbede7a.png)

False Positive (Case 2):
![image](https://user-images.githubusercontent.com/62575608/104067766-a2143e00-51b8-11eb-9c48-50a159bf1a04.png)

**Comment by atiannicelli** [comment]
Two questions/comments: 
1) What would the configurable value for highway_type do? vehicle_only would only look at vehicle ways and not detect if pedestrian ways crossed them?  If I set Pedestrian only would it only look at pedestrian ways that crossed pedestrian ways? 
2) Please also add a new condition: If both crossing candidates don't have level tag, check if one of the candidate is a tunnel (default level=-1)

**Comment by vladlemberg** [comment]
@atiannicelli, 
1. **vehicle only** will look only for a navigable way, which crossing with any types of highway **(current check logic)**. Therefore we are adding **pedestrian only**, which will look for a pedestrian way crossing with all types of highways. one-to-many approach.
2. ok. will add bridge and tunnel to layer check.

**Comment by atiannicelli** [comment]
@vladlemberg sounds good! For automation purposes I just want to make sure that we can configure it to execute both types of checks in one run. So default would be to check both vehicle and pedestrian ways and then IF configured then the user can make it do one or the other?

**Comment by atiannicelli** [comment]
@sayas01 can you assign this to @vladlemberg ?
