### ISSUE TITLE
[Bug] EdgeCrossingEdge is not checking bridge or tunnel layer.  

### ISSUE THREAD

**Issue by vladlemberg** [osmlab/atlas-checks#473]
**Describe the bug**
getInvalidCrossingEdges method is not checking Bridge or Tunnel layer for edge and crossing edge. 

**To fix:** use LayerTag.getTaggedOrImpliedValue instead of LayerTag.getTaggedValue

**To Reproduce**
Run check against both navigable and pedestrian ways. 
shard 8-68-105
ways 163037860 and 323396239 got flagged.
 
**Expected behavior**
ways 163037860 and 323396239  should not be flagged.

**Screenshots & Stack traces**
<img width="565" alt="image" src="https://user-images.githubusercontent.com/62575608/104645680-3886aa80-5664-11eb-91fc-1326fb0aa284.png">

**Environment (please complete the following information):**
any

**Additional context**
This bug will be fixed along with https://github.com/osmlab/atlas-checks/issues/466

**Comment by atiannicelli** [comment]
@sayas01 This could be assigned to @vladlemberg as he is working on a fix to it.

**Comment by vladlemberg** [comment]
fixed. @Bentleysb please close.
