### ISSUE TITLE
[New Check] SimilarTagValueCheck

### ISSUE THREAD

**Issue by brianjor** [osmlab/atlas-checks#485]
**Description**
This check looks for similar values in a tag that are separated by a ‘;’.  

**Requirements**
An Atlas object must meet the following criteria to be considered:
1. Has a tag with multiple values

**Use Cases**
*Case 1: [FP] Destination names are similar but correct*
 - https://www.openstreetmap.org/way/6140462  
 - ![2021-01-27 10 51 48](https://user-images.githubusercontent.com/22751140/106181518-8b775c00-6152-11eb-89fb-09dbae04dd8d.png)

*Case 2: [FP] Ethnonyms are similar but correct*
 - https://www.openstreetmap.org/way/696057937 
 - ![2021-01-27 10 46 55](https://user-images.githubusercontent.com/22751140/106181726-c7122600-6152-11eb-8239-13c20032095c.png)
 
 *Case 3: [TP] Values are similar with only a space being added as the difference*
 - https://www.openstreetmap.org/way/316757724  
 - ![2021-01-27 10 50 17](https://user-images.githubusercontent.com/22751140/106181817-e741e500-6152-11eb-9622-cbc5b2f35e7a.png)

**Further investigation**
There are a lot of FPs from tiger import data on the name_base tag, due to alternative spellings of locations, eg. Annabelle vs Anabelle. Ethnonyms also create a lot of FPs.

**Supported regions**
All countries

**What's not supported (optional):**
This might only support scripts that use an Alphabet type writing system, such as Latin and Cyrillic. So for any tag values typed out in any other script there might be some issues.

**References**
- https://wiki.openstreetmap.org/wiki/Osmose/issues#3060

**Comment by Bentleysb** [comment]
This looks like it could end up being very heavy on FPs. It might be worth trying to get an estimate on the rate before getting to far into development.

**Comment by brianjor** [comment]
Looking at the results that Osmose has (https://osmose.openstreetmap.fr/en/errors?country=usa_washington&item=3060&level=1%2C2%2C3) I'm thinking of having a list of tags to ignore, and possibly a list of values to ignore (ethnonyms, and what ever else pops up), to reduce FP rates.

**Comment by brianjor** [comment]
From a preliminary run just looking for 100% matching tag values in NZL.
All the FPs are from the tags:
- destination -> https://www.openstreetmap.org/way/520976518
- turn:lanes -> https://www.openstreetmap.org/way/627477493
- cables, circuits -> https://www.openstreetmap.org/way/790916533

So it looks like not checking these tags values would be enough as the rest are TP. 
Going to setup the check to do similarity as well and check those results.

**Comment by Bentleysb** [comment]
One other suggestion is to look into how [MixedCaseNameCheck](https://github.com/osmlab/atlas-checks/blob/dev/src/main/java/org/openstreetmap/atlas/checks/validation/tag/MixedCaseNameCheck.java#L119) handles testing against only specific countries/languages. It seems something like that could be useful here.
