### ISSUE TITLE
[Feature Request] Map Roulette Upload supports array of strings for Description and Instructions

### ISSUE THREAD

**Issue by atiannicelli** [osmlab/atlas-checks#492]
**Is your feature request related to a problem? Please describe.**
When uploading issues flagged by atlas checks to a challenge in Map Roulette I would like the ability to create a long winded Description. 

**Describe the solution you'd like**
I'd like to have the "Description" and "Instruction" parameter in the "configuration.conf" file that we specify when running the map_roulette upload command to be either a string (as it is now) OR an array of strings to allow for a long winded description or instruction.

**Describe alternatives you've considered**

**Additional context**
Here is an example of what I'm looking for. Let's say we are uploading a project that includes the LevelCrossingOnRailwayCheck. In the configuration.json that we are specifying with the --config parameter has the following configuration for that check:
```
  "LevelCrossingOnRailwayCheck": {
    "layer.default": 0,
    "railway.filter": "railway->rail,tram,disused,preserved,miniature,light_rail,subway,narrow_gauge",
    "challenge": {
      "description": [
           "Challenge Description: \n",
           "Tasks contain features which are missing or incorrectly tagged as railway:level_crossing.\n",
           "Challenge Instructions: \n",
           "This challenge contains a number of different issues that are all associated with a Level Crossing. ",
           "Basically a railway that crosses a car navigable highway on the same layer should both contain a ",
           "node that has a 'railway=level_crossing' tag. No other objects should have the 'railway=level_crossing' ",
           "tag. Additionally, railway intersections with non-car navigable ways should most often have a ",
           "'railway=crossing' tag instead. This challenge has a number of issues that include auto-fix suggestions ",
           "to make addressing the issues as easy as accepting the suggestions."
      ],
      "blurb": "Fix level crossing railway/highway intersections",
      "instruction": "Open your favorite editor and validate that the buildings are mapped correctly",
      "difficulty": "NORMAL",
      "defaultPriority": "LOW"
    }
  },
```

My hope would be that the challenge description on Map Roulette would look like this:

Challenge Description: 
Tasks contain features which are missing or incorrectly tagged as railway:level_crossing.
Challenge Instructions: 
This challenge contains a number of different issues that are all associated with a Level Crossing. Basically a railway that crosses a car navigable highway on the same layer should both contain a node that has a 'railway=level_crossing' tag. No other objects should have the 'railway=level_crossing' tag. Additionally, railway intersections with non-car navigable ways should most often have a 'railway=crossing' tag instead. This challenge has a number of issues that include auto-fix suggestions to make addressing the issues as easy as accepting the suggestions.

**Comment by atiannicelli** [comment]
@sayas01 Please assign this to @vladlemberg

**Comment by Bentleysb** [comment]
This sounds good to me. I think multi line descriptions and instructions are already possible by just adding new line characters, but I am not opposed to adding the array based formatting of this.

**Comment by seancoulter** [comment]
Sounds good. Note that the challenge instructions can currently be viewed from the challenge homepage. We will monitor whether this requires UI changes in the Instructions field for the task, to fit all the text in

**Comment by atiannicelli** [comment]
String arrays supported now. Closing
