### ISSUE TITLE
[Bug] LineCrossingWaterBodyCheck false positives on ferries, fords, and embankments

### ISSUE THREAD

**Issue by atiannicelli** [osmlab/atlas-checks#497]
**Describe the bug**
The LineCrossingWaterBodyCheck is incorrectly flagging the following cases:
1. Ways that terminate at a node on the edge of a water body that has a `ferry=yes` tag
2. Ways that terminate at a node at the edge of a water body that is also the terminating node for a way that contains the `ford=yes` or` embankment=yes` tag
3. Way cross water bodies that are marked as `intermittent=yes` or `seasonal=yes`
4. Ways that terminate at a node on the edge of a waterbody with a `leisure=slipway` tag

**To Reproduce**
Execute LineCrossingWaterBodyCheck on Argentina. Some MapRoulette screen captures below. 

**Expected behavior**
For each of the cases in the section above I would expect that this check would NOT flag the described situation as an issue. (Note # 4 can go either way, but to reduce the number of issues I would recommend that these water crossings are not flagged.)

**Screenshots & Stack traces**
Case 1
![Screen Shot 2021-02-04 at 3 44 44 PM](https://user-images.githubusercontent.com/5851115/106953041-eb947200-66ff-11eb-9847-97ca4def8865.png)
https://www.openstreetmap.org/way/263326920

Case 2 
![Screen Shot 2021-02-04 at 3 48 06 PM](https://user-images.githubusercontent.com/5851115/106953434-63629c80-6700-11eb-9748-6df308cf526a.png)
https://www.openstreetmap.org/way/770609264

Case 3 
https://www.openstreetmap.org/way/621512550#map=15/-44.0298/-67.2608

**Environment (please complete the following information):**
 - OS: [All]
 - Version [6.1.11]

**Additional context**
NA.

**Comment by seancoulter** [comment]
Hey @atiannicelli , thanks for the analysis on this. Do you have OSM IDs for cases 1-3?

**Comment by atiannicelli** [comment]
@seancoulter I added a few links to the comment and removed the original case 3. Originally I thought there was an issue with ways marked as ford=yes, but I think the edge case is where a road with no ford or embankment terminates on a node that is shared with a waterbody. If that way continues into the waterbody with a ford or embankment then I think that this case should not be flagged. Case 2 is an example of this situation.

**Comment by atiannicelli** [comment]
I'll take this one and work on it.
