### ISSUE TITLE
[Feature Request] OverlappingEdgeCheck one task per set of contiguous overlapping segments

### ISSUE THREAD

**Issue by atiannicelli** [osmlab/atlas-checks#501]
**Is your feature request related to a problem? Please describe.**
Each OverlappingEdgeCheck flag indicates a single segment of two ways that are duplicated. It would be better to group all contiguous segments that are duplicates into one flag.

**Describe the solution you'd like**
Currently the instructions for this check when uploaded to Map Roulette state "Duplicate Highway found for way id 829552865. Overlapping way id(s) 829571967." But if multiple segments are flagged for these two ways each task has the same instructions. It would be nice to have one task that lists all the contiguous segments that overlap for the two ways. Having a task for each segment that is overlapped is too noisy. Once we have an auto-fix suggestion for this check that suggests to delete one of the duplicates we will want a single task for the set of segments instead of one task per segment.
Also, Since OverlappingEdgeCheck has replaced duplicateWaysCheck I would propose removing the documentation docs/checks/duplicateWaysCheck.md 

**Describe alternatives you've considered**
NA

**Additional context**
Good Map Roulette example of two segments on the same duplicated ways
https://maproulette.org/challenge/16317/task/80047048
https://maproulette.org/challenge/16317/task/80047049
Same instructions, but different segment - wouldn't it be nice if it was one task with a list of segments that were all duplicates?

**Comment by brianjor** [comment]
@atiannicelli 
I've started working on this: see [branch](https://github.com/brianjor/atlas-checks/tree/one-task-per-way).

**Comment by brianjor** [comment]
I've got a MR challenge with the first results up. https://maproulette.org/admin/project/42999/challenge/16993/task/84218164/inspect
Does this look like how they should be grouped?

**Comment by atiannicelli** [comment]
Yup - since I'm not an admin I can't inspect, but I saw it here: https://maproulette.org/challenge/16993/task/84218164
Looks good to me - that one is even interesting because it has one section that isn't overlapping in the middle.

The only thing I would change is to remove the anchor. I'm investigating what causes that, but I think that some ways to crates a flag adds a location in the feature list in the json. If you know how to drop that location from the feature list it would look so much better in MR... but obviously not a huge deal and not originally part of this issue so you can choose to ignore it if you want.
