### ISSUE TITLE
[Feature Request] RoadNameGapCheck instructions and bridge enhancement

### ISSUE THREAD

**Issue by atiannicelli** [osmlab/atlas-checks#507]
**Is your feature request related to a problem? Please describe.**
The instructions for RoadNameGapCheck use the word "edge" when it should use the word "way" or "road". The feature ID of the way in question is also not included in the instructions.

**Describe the solution you'd like**
The current instruction for this check looks like this
```
"Edge name Puente Mecano is different from in edge name and out edge name."
```
This should be changed something like this:
```
"The name, 'Puente Mecano', for way id 157600955 is different from the ways it is connected to, "Cruce Longitudinal (Coquiao) - Pumanzano". Consider setting the name so that it is consistent with the other ways."
```
Also, this check needs to be extended so that if the road name gap happens on a bridge (like in this example) that the instructions are altered to instruct the mapper to assign the name of the bridge using the " bridge:name=*" notation.
```
"The name, 'Puente Mecano', for bridge with id 157600955 is different from the ways it is connected to, 'Cruce Longitudinal (Coquiao) - Pumanzano'. Consider setting the name of this way to 'Cruce Longitudinal (Coquiao) - Pumanzano' so that it is consistent with the other ways setting 'bridge:name=Puente Mecano' to save the original name of the bridge."
```
https://maproulette.org/challenge/14920/task/69444772

**Describe alternatives you've considered**

**Additional context**
This request came from a test team that was working on resolving these issues.

**Comment by mm-ciub** [comment]
I believe this can be closed (https://github.com/osmlab/atlas-checks/pull/521)

**Comment by Bentleysb** [comment]
Looks complete.
