### ISSUE TITLE
[Bug] RoadNameGapCheck suggestion when name exists almost never the right thing to do

### ISSUE THREAD

**Issue by atiannicelli** [osmlab/atlas-checks#520]
**Describe the bug**
The roadNameGapCheck suggestion when the gap segment has an existing name today suggests to add that name to the alternatives and then use the in and out segments' names. Seems like a good way to go, but in practice it is almost never the right thing to do.

**To Reproduce**
Execute RoadNameGapCheck and then create a MapRoulette challenge from the results. look through the tasks until you find a task where the gap segment has a current name.

**Expected behavior**
I think, considering the feedback from the mappers, that the suggestion for when the gap segment has a name should be removed. For these cases most of the time the name is almost correct and just needs to be edited a bit instead of saving the current name in the alternate name field.

**Screenshots & Stack traces**
NA

**Environment (please complete the following information):**
 - OS: [All]
 - Version [6.1.13]

**Additional context**

**Comment by mm-ciub** [comment]
I believe this was fixed in https://github.com/osmlab/atlas-checks/pull/521

**Comment by Bentleysb** [comment]
Looks complete.
