### ISSUE TITLE
[Feature Request] OSC support in MapRouletteUploadCommand

### ISSUE THREAD

**Issue by seancoulter** [osmlab/atlas-checks#533]
This is to track support for OSC file uploads using the MapRoulette Upload command. We should be able to upload osc files for individual Tasks in a cooperative challenge. A cooperative challenge is simply a challenge whose edit state can be saved and picked up again by later editors. When a Task has an osc file bundled with it, and it's uploaded, the result is that in-progress/already done work for that Task is loaded in for editors to pick up on.

Here is a sample Task geojson to be used for upload to MR. OSC files can be embedded under "file.content"- 
```
{
  "type": "FeatureCollection",
  "features": [ ... ],            // omitted for readability
  "cooperativeWork": {            // special `cooperativeWork` property
    "meta": {
      "version": 2,               // must be format version `2`
      "type": 2                   // `2` for change file type
    },
    "file": {                     // represents the change file with in-progress work
      "type": "xml",              // only `xml` is currently supported
      "format": "osc",            // only `osc` is currently supported
      "encoding": "base64",       // only `base64` is currently supported
      "content": "..."            // the base64-encoded osc file
    }
  }
}
```

We essentially just need to point the Task to an osc file and put it under "content" in the above geojson. There are 2 approaches - 

1. osc files can be specified in some directory as an arg to the MR upload command. We would need a way to associate each osc file with a Task (maybe by task/checkflag id) so that once we've deserialized a CheckFlag from the logfiles and loaded it into a Task in the MR upload command, we can add the corresponding OSC file to that Task. In the Task class, `setCooperativeWork()` can be overridden to accept an osc file. A new processor can be used in this method that creates the "cooperativeWork.file" geojson above, injects the osc file under 'content', and assigns the value to `Task().cooperativeWork`. `Task.generateTaskCooperativeWork` should then be updated to handle "operations" geojsons for tag fix suggestions as well as "file" geojsons for osc files. Note that the existing `FixSuggestionToCooperativeWorkConvertor` processor is used only for tag-based fix suggestions right now.

2. osc files can be embedded in atlas-check logfiles on a task-by-task basis. This may require updates to the CheckFlagDeserializer to be able to read the new osc data. This would also likely prompt changes to the checks framework to output osc files in their checkflags. Due to changes and complexities needed for this approach, this approach is not recommended.

Readings: https://learn.maproulette.org/documentation/creating-cooperative-challenges/

**Comment by atiannicelli** [comment]
@sayas01 Please assign to @vladlemberg

**Comment by vladlemberg** [comment]
@sayas01, @Bentleysb, I believe this task has finished by Taylor. Please close this issue.
