### ISSUE TITLE
[Bug] Problem with running Atlas Checks in a Spark Cluster

### ISSUE THREAD

**Issue by mnogacka** [osmlab/atlas-checks#549]
**Describe the bug**
I'm trying to run Atlas Checks in a Spark Cluster.

**To Reproduce**
For now I tried running atlas-check version 6.1.17 and 6.1.12 on machines with java 11, spark 3.0.1, and command to submit an atlas check spark job:
            cmd = (
                "/opt/spark/bin/spark-submit"
                + " --class=org.openstreetmap.atlas.checks.distributed.ShardedIntegrityChecksSparkJob"
                + " --master=local[{}]".format(self.processes)
                + " --conf='spark.driver.memory={}g'".format(self.memory)
                + " --conf='spark.executor.userClassPathFirst=true'"
                + " --conf='spark.jars.packages=com.google.protobuf:protobuf-java:2.5.0'"
                + " --conf='spark.rdd.compress=true'"
                + " {}".format(jarFile)
                + " -maxPoolMinutes=2880"
                + " -input='{}'".format(self.atlasInDir)
                + " -output='{}'".format(self.atlasOutDir)
                + " -outputFormats='{}'".format(self.formats)
                + " -countries='{}'".format(self.countries)
                + " -configFiles='{}'".format(atlasConfig)
                + " > {} 2>&1 &".format(self.atlasCheckLog)
            )

call:
'''
 Submitting spark job: /opt/spark/bin/spark-submit --class=org.openstreetmap.atlas.checks.distributed.ShardedIntegrityChecksSparkJob --master=local[5] --conf='spark.driver.memory=192g' --conf='spark.executor.userClassPathFirst=true' --conf='spark.jars.packages=com.google.protobuf:protobuf-java:2.5.0' --conf='spark.rdd.compress=true' /tmp/atlas-checks.jar -maxPoolMinutes=2880 -input='/home/ubuntu/input/' -output='/home/ubuntu/output/' -outputFormats='geojson' -countries='COL' -configFiles='file:///tmp/configuration.json' > /home/ubuntu/log/atlasCheck.log 2>&1 &
'''

As the result I receive same error:

```
ERROR Executor: Exception in task 2.0 in stage 0.0 (TID 2)
java.lang.ClassCastException: class org.openstreetmap.atlas.geography.sharding.DynamicTileSharding cannot be cast to class org.openstreetmap.atlas.geography.sharding.Sharding (org.openstreetmap.atlas.geography.sharding.DynamicTileSharding is in unnamed module of loader org.apache.spark.util.MutableURLClassLoader @134c370e; org.openstreetmap.atlas.geography.sharding.Sharding is in unnamed module of loader org.apache.spark.util.ChildFirstURLClassLoader @1f782c05)
	at org.openstreetmap.atlas.checks.distributed.ShardedIntegrityChecksSparkJob.lambda$produceFlags$7fe438cb$1(ShardedIntegrityChecksSparkJob.java:366)
	at org.apache.spark.api.java.JavaPairRDD$.$anonfun$pairFunToScalaFun$1(JavaPairRDD.scala:1044)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:194)
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:62)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:446)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:449)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
I've tried to follow the instructions in docs but those are actually describing procedure for atlas-check in version 4.0.4 and spark 1.6.0. 
If there is a mistake or missing some parameter in spark-submit command, please let me now.

**Expected behavior**
My intention is to run atlas-checks on spark cluster for given country for starters, eventually I would like to run whole world on it..

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS, 20.04
 - Java: 11
 - Spark: 3.0.1

**Comment by seancoulter** [comment]
Hi @mnogacka , it looks like there was some problem loading classes in your Spark environment. Could you try removing the `spark.driver.userClassPathFirst` param, rebuilding the project, and executing?

**Comment by mnogacka** [comment]
Yes, I used wrong params. I've change it to:
```
            cmd = (
                "/opt/spark/bin/spark-submit"
                + " --class=org.openstreetmap.atlas.checks.distributed.ShardedIntegrityChecksSparkJob"
                + " --master=local[{}]".format(self.processes)
                + " --conf='spark.driver.memory={}g'".format(self.memory)
                + " --conf='spark.rdd.compress=true'"
                + " --conf='spark.driver.userClassPathFirst=true'"
                + " --packages='com.google.protobuf:protobuf-java:2.5.0'"
                + " {}".format(jarFile)
                + " -maxPoolMinutes=2880"
                + " -input='{}'".format(self.atlasInDir)
                + " -output='{}'".format(self.atlasOutDir)
                + " -outputFormats='{}'".format(self.formats)
                + " -countries='{}'".format(self.countries)
                + " -configFiles='{}'".format(atlasConfig)
                + " > {} 2>&1 &".format(self.atlasCheckLog)
            )
```

it works now.
