### ISSUE TITLE
[Bug] ShortSegmentCheck flags are mostly False Positives 

### ISSUE THREAD

**Issue by atiannicelli** [osmlab/atlas-checks#557]
**Describe the bug**
The ShortSegmentCheck seems to want to flag edge/way segments that are too short, but in practice I see that OSM ways that don't have any short segments are being flagged.  

**To Reproduce**
Execute the ShortSegmentCheck

**Expected behavior**
I think that this check wants to find way segments that are very short for no reason. It may be that this check needs to be converted to consider way segments instead of edge segments??? Anyway, I don't think that most of the flagged issues that I have seen are actually short segments. I have added a couple MapRoulette examples of ShortSegmentCheck flags that are not short segments. The issue MAY be that some of these are near boundaries. Is it possible that the edge segment is being segmented internally in atlas when a boundary is involved? 

Also, the instructions should be altered to say "way" instead of "edge" and use the OSMID instead of the edge ID. 
"This edge 41895328001000 is short (length < 1 m) and it is connected to node 432327349000000 that has less than 3 connections."
should become:
"A segment of way 41895328 is short (length < 1 m) and it is connected to node 432327349 that has less than 3 connections."

**Screenshots & Stack traces**
https://maproulette.org/admin/project/43639/challenge/18416/task/95410708/inspect
<img width="1750" alt="Screen Shot 2021-05-20 at 4 34 02 PM" src="https://user-images.githubusercontent.com/5851115/119045260-34a7c380-b989-11eb-9a0a-eef1b155062d.png">
`{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    34.933394,
                    31.343115
                ]
            },
            "properties": {}
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    34.933394,
                    31.343115
                ]
            },
            "properties": {
                "flag:check": "Israel - ShortSegmentCheck",
                "flag:generator": "Atlas Checks",
                "synthetic_highlight_point": "yes"
            }
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "LineString",
                "coordinates": [
                    [
                        34.933394,
                        31.343115
                    ],
                    [
                        34.9333939,
                        31.3431133
                    ]
                ]
            },
            "properties": {
                "ref": "60",
                "oneway": "yes",
                "highway": "trunk",
                "itemType": "Edge",
                "maxspeed": "90",
                "identifier": "353241992000000",
                "osmIdentifier": "353241992",
                "last_edit_time": "1585303650000",
                "iso_country_code": "ISR",
                "last_edit_user_id": "10294500",
                "last_edit_version": "10",
                "last_edit_changeset": "82708010",
                "last_edit_user_name": "OrDal"
            }
        }
    ]
}`

<img width="1702" alt="Screen Shot 2021-05-20 at 4 35 55 PM" src="https://user-images.githubusercontent.com/5851115/119045425-746eab00-b989-11eb-8bd2-44f5c63e1088.png">
`{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    34.9645594,
                    32.1731909
                ]
            },
            "properties": {}
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    34.9645594,
                    32.1731909
                ]
            },
            "properties": {
                "flag:check": "Israel - ShortSegmentCheck",
                "flag:generator": "Atlas Checks",
                "synthetic_highlight_point": "yes"
            }
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "LineString",
                "coordinates": [
                    [
                        34.9645594,
                        32.1731909
                    ],
                    [
                        34.96456,
                        32.173191
                    ]
                ]
            },
            "properties": {
                "ref": "55",
                "highway": "trunk",
                "surface": "paved",
                "itemType": "Edge",
                "identifier": "41895328000000",
                "osmIdentifier": "41895328",
                "last_edit_time": "1502379725000",
                "iso_country_code": "ISR",
                "last_edit_user_id": "5730547",
                "last_edit_version": "13",
                "last_edit_changeset": "51005240",
                "last_edit_user_name": "דוד-צבי"
            }
        }
    ]
}`

**Environment (please complete the following information):**
 - OS: [all]
 - Version [6.1.19]

**Additional context**
If this check is not relevant to OSM ways (and is edge specific then we should just specify that in the docs.

**Comment by xiaohongtang2** [comment]
I will send PR for fix this issue

**Comment by atiannicelli** [comment]
Fixed! Thanks!
