### ISSUE TITLE
lineCrossingWaterBodyCheck leading to bad edits

### ISSUE THREAD

**Issue by andrewharvey** [osmlab/atlas-checks#561]
I'm not sure if this is the correct place to report but the check at https://github.com/osmlab/atlas-checks/blob/dev/docs/checks/lineCrossingWaterBodyCheck.md is being used by Facebook mappers to update in Australia, however I'm finding a number of these changes not correct. So I'll post them here?

1. https://osmcha.org/changesets/105459547 the path and the water object were never intersecting to begin with

**Comment by andrewharvey** [comment]
2. https://osmcha.org/changesets/105460554 it was changed to the water and path don't connect, but in this case the paths go to the waters edge so should connect

**Comment by atiannicelli** [comment]
1. I'm not sure why the mapper added a node to that way indicated in the changeset (566314737). The issues as flagged in task https://maproulette.org/task/94126725 was trying to flag the fact that the last node of way 48731943 ends on the edge of the water body 531128566. The check looks for ways that terminate at the water's edge that don't have a tag on that intersecting node to indicate what the connection to the water body is. (e.g. slipway, ferry, etc)
2. This changeset was trying to fix https://maproulette.org/task/94128928 which indicates that both 332749248 and 332750251 end at the waters edge without a tag on that node to indicate what the connection is (e.g. slipway, dock, etc)

The specific filter we use to indicate that a node in a way is allowed to connect to a water body edge is:
"ferry->!no&ferry->*|ford->!no&ford->*|leisure->slipway|amenity->ferry_terminal"
Generally, if a path ends at a body of water then we have been ending the way just before it gets to the water body feature.

It sounds like you would rather allow the ways to connect to the water's edge without a special tag to indicate what the connection is?

I have sent a note directly to the mapper that was working on the challenge to ask her to pause edits for this challenge until we resolve this issue - we by no means want to make edits that cause issues or that are inaccurate.

**Comment by andrewharvey** [comment]
> I'm not sure why the mapper added a node to that way indicated in the changeset (566314737). The issues as flagged in task https://maproulette.org/task/94126725 was trying to flag the fact that the last node of way 48731943 ends on the edge of the water body 531128566. The check looks for ways that terminate at the water's edge that don't have a tag on that intersecting node to indicate what the connection to the water body is. (e.g. slipway, ferry, etc)

Oh that makes more sense, I should have checked the actual MapRoulette task.

So these are both the same issue then, a way terminating at the waters edge.

> Generally, if a path ends at a body of water then we have been ending the way just before it gets to the water body feature.

Do you know of prior discussion of this for OSM?

For example from the second task, https://www.openstreetmap.org/way/332749248/history is terminating at the water edge, but I think it makes sense to connect because it helps show the access point to the water, especially here because the water area is tagged as a leisure=swimming_area https://www.openstreetmap.org/way/332749224. Because it's a walking path and not for boats it's not a slipway, or a ford or a ferry terminal, just simply the path leads to the water. I'm not aware of any special tag in OSM you could add to the node.

**Comment by atiannicelli** [comment]
Yup - both the same issue.

I tend to agree with you here. I thought about it a bit and I think that it probably makes sense to allow highways tagged as any type of foot path to connect directly to the water's edge and terminate there. 

highway=(footway|bridleway|steps|corridor|path)

I would still flag if these types of paths crossed over the water without a tag that indicated the type of crossing.

I will discuss this with my team and hopefully get feedback from the atlas checks developers as well next week. Thanks for bringing this to our attention.

**Comment by andrewharvey** [comment]
Another conceivable example is a natural rock pool/ocean bath, some of these are tagged leisure=swimming_pool so not caught up here but others might be natural=water, and you might have highway=steps leading into the water area, as the steps provide access to the pool and usually extend below the water mark.

https://www.openstreetmap.org/way/948582481 is an example, though in this case I've terminated the steps way on the water outline, but on the imagery you can see they actually extend into the water.

**Comment by andrewharvey** [comment]
With these examples, I'm not saying it's not helpful to flag these, because sometimes they might be map errors to be corrected, just downstream users of the flagged issues (like MapRoulette users) should be aware that it's not necessarily always an issue.

**Comment by atiannicelli** [comment]
I think the atlas checks project is trying to flag issues to be corrected. I don't think we want to flag features that are possibly issues, so I am going to recommend to my team that the following changes be made to this check:

1) ways that end on the edge of a water body with the following tags should not be flagged as issues:
      highway=(footway|bridleway|steps|corridor|path)
2) ways that cross into a water body (and end there) with the `highway=steps` should also not be flagged.

**Comment by Bentleysb** [comment]
Hey @andrewharvey, thanks for creating this issue, and thanks @atiannicelli for digging into it. I agree it looks like there needs to be an update to better handle paths and the like, and the proposed changes look good.

**Comment by vladlemberg** [comment]
Hi @Bentleysb, please assign this task to me.

**Comment by vladlemberg** [comment]
Hi @sayas01, please close this issue. Its resolved.

**Comment by atiannicelli** [comment]
@andrewharvey, I believe we have addressed the issues you identified in this issue. 

Issues like https://maproulette.org/task/94126725 will no longer be flagged. Also Way 332749224 and the like are no longer flagged.

Feel free to take a look at https://maproulette.org/browse/challenges/17379 and see what you think of the issues flagged by that check in Australia. If you feel this specific issue has been addressed please close this issue. If you see any other issues, please let us know.

**Comment by vladlemberg** [comment]
@Bentleysb, please close this issue.
