### ISSUE TITLE
[Feature Request] Add flag name override in config file

### ISSUE THREAD

**Issue by atiannicelli** [osmlab/atlas-checks#576]
**Is your feature request related to a problem? Please describe.**
In the configuration file for atlas checks each section is identified by a name of the check to execute, but I was wondering if we could add a new parameter in the configuration for each check that identifies the check code to execute and then start using the section header as an output check name.

**Describe the solution you'd like**
I'd like to be able to do this: (I changed the first line of each section, added the "check", and changed the parameters)
```
  "EdgeCrossingEdgeCheckCars": {
    "check": "EdgeCrossingEdgeCheck",
    "minimum.highway.type": "no",
    "maximum.highway.type": "motorway",
    "car.navigable": true,
    "pedestrian.navigable": false,
    "crossing.car.navigable": true,
    "crossing.pedestrian.navigable": false,
    "indoor.mapping": "indoor->*|highway->corridor,steps|level->*",
    "challenge": {
      "description": "Tasks contain ways that do not have shared nodes but cross each other.",
      "blurb": "Crossing Ways",
      "instruction": "Open your favorite editor and connect the ways at the point of intersection.",
      "difficulty": "EASY"
    }
  },
  "EdgeCrossingEdgeCheckPedestrians": {
    "check": "EdgeCrossingEdgeCheck",
    "minimum.highway.type": "no",
    "maximum.highway.type": "motorway",
    "car.navigable": false,
    "pedestrian.navigable": true,
    "crossing.car.navigable": false,
    "crossing.pedestrian.navigable": true,
    "indoor.mapping": "indoor->*|highway->corridor,steps|level->*",
    "challenge": {
      "description": "Tasks contain ways that do not have shared nodes but cross each other.",
      "blurb": "Crossing Ways",
      "instruction": "Open your favorite editor and connect the ways at the point of intersection.",
      "difficulty": "EASY"
    }
  },
```
And the flags file produced would use the EdgeCrossingEdgeCheck code and the configuration options from the section, but then use the value from the section header (e.g. EdgeCrossingEdgeCheckCars) as the "generator" value. This would allow us to execute the same check with multiple configurations in the same run.

**Describe alternatives you've considered**
The alternative is to run the atlas checks again with a separate configuration file. The issue with this is that then there is no way to tell the two different runs apart in the flags file as the "generator" value will always be the same for both runs.
The other alternative is to separate checks that we think we will want to run with different configurations. This is probably the best way to go if we don't want to add this functionality, but it is hard to tell if this is necessary.

**Additional context**

**Comment by Bentleysb** [comment]
I very much like the idea of being able to run a check multiple times with one configuration. It is likely going to take a lot of refactoring, but is probably worth it. 
If possible I would like to see some backwards compatibility, and a way to use overrides instead of having to completely reconfigure all parameters. My thought is a structure like the following would work:
```
"EdgeCrossingEdgeCheck": {
  "name": "EdgeCrossingEdgeCheckCars",
  "minimum.highway.type": "no",
  "maximum.highway.type": "motorway",
  "car.navigable": true,
  "pedestrian.navigable": false,
  "crossing.car.navigable": true,
  "crossing.pedestrian.navigable": false,
  "indoor.mapping": "indoor->*|highway->corridor,steps|level->*",
  "challenge": {
    "description": "Tasks contain ways that do not have shared nodes but cross each other.",
    "blurb": "Crossing Ways",
    "instruction": "Open your favorite editor and connect the ways at the point of intersection.",
    "difficulty": "EASY"
  },
  "additional.runs": [
    {
      "name": "EdgeCrossingEdgeCheckPedestrians",
      "car.navigable": false,
      "pedestrian.navigable": true,
      "crossing.car.navigable": false,
      "crossing.pedestrian.navigable": true
    }
  ]
}
```
The `name` param would get used as the generator value, if it exists, otherwise it would default to the check name. The check would be run once using the top level params and once for each set of params in `additional.runs`. Any params not defined in the objects under `additional.runs` would default to the top level params (or the hard coded defaults if they don't exist in the config at all).
