### ISSUE TITLE
[Feature Request] LevelCrossingOnRailwayCheck refinement request

### ISSUE THREAD

**Issue by atiannicelli** [osmlab/atlas-checks#577]
**Is your feature request related to a problem? Please describe.**
Many of the issues that this check is flagging are intersections between a road and disused rail. I believe that the best tag to add to these nodes is disused:railway=level_crossing
Also, there is probably no real need to flag level crossing on service ways or lower.

**Describe the solution you'd like**
Add a refinement to the LevelCrossingOnRailwayCheck to recognize that the railway is disused and if so then recommend to add `disused:railway=level_crossing` tag to that intersection. I think this can be a auto suggestions case.
Also, we should add a parameter to this check to be able to control what road types we care about. I think that service roads and lower can probably be ignored as they seem to happen in parking lots and undefined spaces that don't really need a crossing node.

**Describe alternatives you've considered**
The way it is makes it tedious to fix these issues...

**Additional context**
see this disused rail to see all the intersections that could be fixed with this suggestion.
https://www.openstreetmap.org/way/771448302

**Comment by atiannicelli** [comment]
@Bentleysb @sayas01 - if this sounds good to you then I will work on this one.

**Comment by vladlemberg** [comment]
@sayas01, please assign this to me

**Comment by vladlemberg** [comment]
Hi @sayas01, please close this issue. Its merged.
