### ISSUE TITLE
RouteRelationCheck

### ISSUE THREAD

**Issue by lucylu9161** [osmlab/atlas-checks#600]
**Description:**
This check handles the five classes in OSMOSE 1260 (Osmose/1260):
Class 1 "The track of this route contains gaps" :
Class 2 "The stop or platform is too far from the track of this route" :
Class 3 "Non route relation member in route_master relation" :
Class 4 "Public transport relation route not in route_master relation" :
Class 5 "network, operator, ref, colour tag should be the same on route and route_master relations"

One example of a route contains gaps in its track from Open Street Map is:

 
![image](https://user-images.githubusercontent.com/45083974/129070787-ea721ac8-52fe-4bd6-b534-5960c52c36cd.png)

Supported regions
No Restrictions

**References**
https://wiki.openstreetmap.org/wiki/Osmose/issues#1260

**Comment by atiannicelli** [comment]
I believe this can be closed.

**Comment by lucylu9161** [comment]
Closed.

Thanks,
Lucy
