### ISSUE TITLE
[Check Improvement] UnusualLayerTagsCheck

### ISSUE THREAD

**Issue by nelkapelmenka** [osmlab/atlas-checks#611]
**Description**
The improvement of the UnusualLayerTagsCheck. Everything below is the addition to the check. Checking if the object with key:layer less or greater than 0 has incorrect tags. 

**Requirements**
 - Is a Way or Node
 - Layer tag exists and is not 0

**Use Cases**
*Case 1: [Landuse feature not on ground.]*
 - If the object has a landuse tag. Landuse is used to describe "the primary use of land by humans."
 - [Way: 94449954](https://www.openstreetmap.org/way/94449954)
![image](https://user-images.githubusercontent.com/55819977/130150560-2d9e4658-9c72-4215-b3dc-791962c67569.png)

*Case 2: [Natural feature underground.]*
 - If the tag layer is less than 0 and the tag natural is not "water"
 - [Way: 25314718](https://www.openstreetmap.org/way/25314718)
![image](https://user-images.githubusercontent.com/55819977/130152149-d5cf6d48-bcb6-4c4d-bf06-70e4983d92f2.png)

*Case 3: [Highway underground and no tunnel.]*
 - Layer tag is less than 0, highway tag is not "steps", the indoor tag doesn't exist or is "no" and the tunnel tag doesn't exist or is "no".
 - [Way: 121520872](https://www.openstreetmap.org/way/121520872)
![image](https://user-images.githubusercontent.com/55819977/130152185-47b87072-0685-4bb9-9ebe-e83da9b30a57.png)

*Case 4: [Long highway underground and no tunnel.]*
 - The same idea as Case 3 but only if the Way is more than 3 nodes
 - [Way: 587740859](https://www.openstreetmap.org/way/587740859)
![image](https://user-images.githubusercontent.com/55819977/130152468-991c93a6-69ac-472f-8970-668791888093.png)

*Case 5: [Highway above ground and no bridge.]*
 - Layer tag is above 0, highway tag exists and is not "steps", indoor tag doesn't exist or is "no", bridge tag doesn't exist or is "no", and man_made tag is not "pier"
 - [Way: 194101434](https://www.openstreetmap.org/way/194101434)
![image](https://user-images.githubusercontent.com/55819977/130152733-65f08c11-6f0a-4a77-adfb-317ff85fba63.png)

*Case 6: [Long highway above ground and no bridge.]*
 - Same as Case 5 but the way has more than 3 nodes
 - [Way: 356910749](https://www.openstreetmap.org/way/356910749)
![image](https://user-images.githubusercontent.com/55819977/130152905-c0b255bd-3383-4912-8ae6-9cc1ce400370.png)

*Case 7: [Waterway underground and no tunnel.]*
 - The layer is less than 0, the waterway tag exists or the natural tag is "water", the tunnel tag doesn't exist or is "no", and the location tag doesn't exist or is not "underground."
 - [Way: 290833931](https://www.openstreetmap.org/way/290833931) 
![image](https://user-images.githubusercontent.com/55819977/130153526-67339205-9464-45e7-bc82-744c6e842fab.png)

*Case 8: [Long waterway underground and no tunnel.]*
 - Same as Case 7 but only for way with over 3 nodes
 - [Way: 23066184](https://www.openstreetmap.org/way/23066184)
![image](https://user-images.githubusercontent.com/55819977/130154222-0d5889a1-fd1a-4fa2-8d2e-89310e062c13.png)

*Case 9: [Waterway above ground and no bridge.]*
 - The layer tag is above 0, the bridge tag doesn't exist or is "no", and the waterway tag exists or the natural tag is "water".
 - [Way: 166798321](https://www.openstreetmap.org/way/166798321)
![image](https://user-images.githubusercontent.com/55819977/130154350-8b2659d1-4bbe-432f-a803-9e2a9fb2f710.png)

*Case 10: [Long waterway above ground and no bridge.]*
 - Same as Case 9 but for ways with over 3 nodes
 - [Way: 686335070](https://www.openstreetmap.org/way/686335070)
![image](https://user-images.githubusercontent.com/55819977/130155303-6bc74909-04b9-49db-8d1f-f4b174144823.png)

**References**
[OSM Wiki Issue Page](https://wiki.openstreetmap.org/wiki/Osmose/issues#4110)
[Osmose backend](https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagRemove_Layer.py)

**Comment by Bentleysb** [comment]
This looks like it would be a good enhancement to [UnusualLayerTagsCheck](https://github.com/osmlab/atlas-checks/blob/dev/docs/checks/unusualLayerTagsCheck.md).
