### ISSUE TITLE
[New Check] Admin Boundary Role Check

### ISSUE THREAD

**Issue by atiannicelli** [osmlab/atlas-checks#626]
**Description**
Add a check that is designed to make the use of the "label" and "admin_centre" boundary relation roles more consistent. In some admin boundary relations mappers have made the node that represents the center of the relation an "admin_centre", this is incorrect as the admin_centre should be the node that represents the administrative center of the boundary, not the physical center. When the boundary is a country then the admin_centre should be the node that represents the state within that relation. For a state relation the admin_centre should be a city. The wiki doesn't specify what the admin_centre of a city relation should be so probably no admin center is appropriate for cities. In many cases it would make sense to change the role of a city's "admin_centre" member node to the "label" role to indicate the city's physical center.

**Requirements**
Check Candidate 
 - Is a `Relation`
 - Has Tags: `boundary` == `administrative` && `type` == `boundary` && 'admin_level' key exists && 'admin_level` != '""' && 'admin_level' <= 8

**Use Cases**
Flag admin relations with either of the two following conditions:
1) Relation has a node member with role="admin_centre" where "name" tag on the node is the same content as the "name" tag on the relation. This indicates that the relation has an admin_centre equivalent to itself which is usually incorrect. Suggest that the node should have "label" role instead of "admin_centre".
2) Relation has no member with role="admin_centre" or role="label" and the relation boundary contains a node with the same name as the relation. This indicates that a node indicating the correct location for the boundary exists, but the relation doesn't refer to it as the label. Suggest that the node should be a member of the relation with role="label" 

*Case 1: City relation with admin_centre member. (Phoenix, AZ)*
 - The [City of Phoenix is represented by a node](https://www.openstreetmap.org/node/150964064) with place="city" and name="Phoenix". This node currently is also a member of the [city of phoenix relation](https://www.openstreetmap.org/relation/111257) with a role="admin_centre". This is incorrect as the administration center of a city relation should not be a city node. 
 - https://www.openstreetmap.org/relation/111257 (Note: "Node Phoenix (150964064) as admin_centre")

<img width="888" alt="Screen Shot 2021-09-27 at 1 34 25 PM" src="https://user-images.githubusercontent.com/5851115/134957664-7bca2c05-f95e-464b-a782-0ba8000bef21.png">

*Case 2: City relation with no label (Redlands, CO)
- The [Locality of Redlands, CO relation](https://www.openstreetmap.org/relation/113221) has no member with a role of "label". Inside the boundary there exists a [node with the name="Redlands" and place="hamlet"](https://www.openstreetmap.org/node/151698697) indicating that this node would be the correct "label" for the relation.
- https://www.openstreetmap.org/relation/113221
- https://www.openstreetmap.org/node/151698697

<img width="1792" alt="Screen Shot 2021-09-27 at 1 45 12 PM" src="https://user-images.githubusercontent.com/5851115/134958975-06b2bffa-2530-4d93-b03e-7bc51dabeae6.png">
<img width="1060" alt="Screen Shot 2021-09-27 at 1 46 08 PM" src="https://user-images.githubusercontent.com/5851115/134959104-0672cf89-3cb7-4d47-b559-e53233739a70.png">

**Further investigation**
I discussed this on the US OSM slack and got feedback that this is a common issues that is global. [Paris](https://www.openstreetmap.org/relation/1641193) has the same issue.
There are currently about 74,761 boundary relations with no node roles (no label or admin_centre).
There are currently about 60 boundary relations with an "**admin_centre**" role (misspelled) 
There are currently over 10,000 boundary relations with admin_level=8 and with an "**admin_centre**" role but no label role

**Supported regions**
"All countries"

**What's not supported (optional):**
Do not include admin_level greater than 8. 
Also, it will be interesting to see if more than a name check is required. It may be necessary to add more qualification to the nodes that we search for inside the boundary relation. There are cases where the boundary might be a county boundary and contain a city inside it with the same name. In that case it may be appropriate for the county to have an admin_centre that is the city within the county with the same name.

**References**
Relevant Wiki pages:
 - https://wiki.openstreetmap.org/wiki/Relation:boundary#Relation_members
 - https://wiki.openstreetmap.org/wiki/Key:place

**Comment by Bentleysb** [comment]
Sounds like there could be some interesting edge cases to figure out, but overall this sounds great to me.

**Comment by vladlemberg** [comment]
@Bentleysb, please assign this task to me.

**Comment by atiannicelli** [comment]
It turns out that this check is not possible using atlas infrastructure. The issue is that there is a requirement to shard the pbf into smaller atlas files to be able to scan the entire planet quickly. We have found that many of the admin boundary relations are not available in the final atlas files that we scan for atlas checks. This check would be better as a database validation scan that can simply fetch all the admin boundary relations and inspect the admin_center member of the relation.
