### ISSUE TITLE
[Bug] ConnectivityCheck Dead End Logic Does Not Account For Reverse Edges

### ISSUE THREAD

**Issue by Bentleysb** [osmlab/atlas-checks#627]
**Describe the bug**
After https://github.com/osmlab/atlas-checks/pull/619 there were some unexpected drops in flags. These flags consisted of "dead end" nodes connected to one main and one reverse edge. It appears the new dead end logic only works for one way roads, that do not have a reverse edge. 

**To Reproduce**
1. Run ConnectivityCheck in atlas check 6.2.4
2. Run ConnectivityCheck in atlas check 6.2.6
3. Compute differences in flags

**Expected behavior**
There sorts of flags should have been maintained with the new logic.

**Screenshots & Stack traces**
Missing flag examples:

1. Node [6230687868](https://www.openstreetmap.org/node/6230687868) is likely supposed to be connected to: way [525179930](https://www.openstreetmap.org/way/525179930)
![Screen Shot 2021-09-28 at 4 01 06 PM](https://user-images.githubusercontent.com/24948563/135177035-bf4266a6-4c78-4c1b-904c-6bc6b3a5dfe7.png)

2. Node [7148640414](https://www.openstreetmap.org/node/7148640414) is likely supposed to be connected to: way [855789796](https://www.openstreetmap.org/way/855789796)
![Screen Shot 2021-09-28 at 4 03 01 PM](https://user-images.githubusercontent.com/24948563/135177171-7e1ca13a-9b4c-479a-8b37-9a7f860c61a0.png)

**Comment by vladlemberg** [comment]
@Bentleysb, please assign it to me. thanks!
