### ISSUE TITLE
[Bug] OverlappingEdgeCheck Pedestrian Area Definition

### ISSUE THREAD

**Issue by Bentleysb** [osmlab/atlas-checks#637]
**Describe the bug**
The current definition of a pedestrian area in OverlappingEdgeCheck does not include the common tagging practice of highway=footway and area=yes (see the areas section [here](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dfootway)). The check should be updated to include this.

**To Reproduce**
1. Run OverlappingEdgeCheck in MEX
2. Observe that [way 344030479](https://www.openstreetmap.org/way/344030479) is flagged for overlapping [way 344030705](https://www.openstreetmap.org/way/344030705)

**Expected behavior**
When the check is configured to ignore overlap with pedestrian areas, overlap with Edges tagged as highway=footway and area=yes should not be flagged.

**Comment by atiannicelli** [comment]
@sayas01 can you assign this to @vladlemberg if no one else is looking at it.
