### ISSUE TITLE
[Bug] LevelCrossingOnRailwayCheck doesn't recognize disused level_crossing

### ISSUE THREAD

**Issue by atiannicelli** [osmlab/atlas-checks#672]
The LevelCrossingOnRailwayCheck doesn't recognize disused level_crossing correctly. When there is a disused railway and that crosses a highway then there should be a level_crossing node. But it is also valid to have a disused:railway=level_crossing node at that intersection. 

Run the LevelCrossingOnRailwayCheck on the USA and look for places where disused railways are flagged as not having level crossing nodes over intersecting highways.

Disused railways that cross highways and intersect with a disused:railway=level_crossing should NOT be flagged.

This screen shot shows task https://maproulette.org/challenge/25236/task/125239209 flagging an intersection that is valid:
![Screen Shot 2022-04-18 at 12 30 09 PM](https://user-images.githubusercontent.com/5851115/163840045-f126c8b6-a1cf-4310-b5ee-1cd63b0abda3.png)

Here is the node and the good tag:
![Screen Shot 2022-04-18 at 12 30 52 PM](https://user-images.githubusercontent.com/5851115/163840119-3665b815-0df0-4b49-8d15-dc97b3aca104.png)

**Comment by atiannicelli** [comment]
Please assign this to @vladlemberg

**Comment by vladlemberg** [comment]
corresponded RP to handle this issue submitted. https://github.com/osmlab/atlas/pull/787

**Comment by vladlemberg** [comment]
@Bentleysb, please close this issue.
