### ISSUE TITLE
[Bug] LevelCrossingOnRailwayCheck doesn't recognize railway=tram_level_crossing as valid tram/road intersection

### ISSUE THREAD

**Issue by atiannicelli** [osmlab/atlas-checks#675]
The flags intersections where a railway=tram and road intersect even if that intersection is tagged with railway=tram_level_crossing. This is a perfectly legal intersection and should not be flagged.

https://maproulette.org/challenge/25236/task/129680001
![Screen Shot 2022-05-09 at 1 45 51 PM](https://user-images.githubusercontent.com/5851115/167467316-3e778f50-cf0a-4b6d-8ab2-b1dd4151d1be.png)
![Screen Shot 2022-05-09 at 1 46 26 PM](https://user-images.githubusercontent.com/5851115/167467406-b6eb4f56-a382-4a8d-b48c-f1f9db34cb79.png)
https://www.openstreetmap.org/node/8329479001

**Comment by vladlemberg** [comment]
@Bentleysb, please assign this ticket to me. Thanks!
