### ISSUE TITLE
Issue: Build failed

### ISSUE THREAD

**Issue by rusionut28** [osmlab/atlas-checks#690]
I'm getting the error: java.lang.OutOfMemoryError: Java heap space for .pbf files larger than 20MB 

How to resolve this issue?

**Comment by Bentleysb** [comment]
Hi @rusionut28,

It sounds like you need to increase the amount of memory the java vm is allowed to use. If you are running using the gradle or docker run command you can do this by giving the argument `-Dorg.gradle.jvmargs=-Xmx16g`. Replace the 16g with whatever amount of memory your machine has that you want to give.

**Comment by rusionut28** [comment]
For some reason it doesn't get past 4.7GB on MacOS Ventura  
[Terminal Saved Output.txt](https://github.com/osmlab/atlas-checks/files/10831494/Terminal.Saved.Output.txt)

**Comment by Bentleysb** [comment]
Hmm, I'm not sure why setting the JVM arguments is not working from the command line. You could also try setting them here: https://github.com/osmlab/atlas-checks/blob/dev/gradle/execute.gradle#L53

**Comment by rusionut28** [comment]
> Hmm, I'm not sure why setting the JVM arguments is not working from the command line. You could also try setting them here: https://github.com/osmlab/atlas-checks/blob/dev/gradle/execute.gradle#L53

That worked, thanks a lot!
