### ISSUE TITLE
Layer Tag Method Change Breaking Checks

### ISSUE THREAD

**Issue by Bentleysb** [osmlab/atlas-checks#77]
A jump in false positive flags for both UnusualLayerTagsCheck and EdgeCrossingEdgeCheck has been traced back to a change in the LayerTag method that is used in both.
In https://github.com/osmlab/atlas-checks/pull/62 both checks were altered to use the `getTaggedValue` method in place of the `getTaggedOrImpliedValue`method that was breaking the checks due to a return type alteration. Unfortunately, this meant the loss of the default value system the checks are dependent on. This has caused false positive rates to jump 40%+ for UnusualLayerTagCheck and 50%+ for EdgeCrossingEdgeCheck, in some countries. 

Examples:
    UnusualLayerTagCheck:
        https://www.openstreetmap.org/way/465528364 is now improperly flagged, because it does not have a layer tag. This would have been avoided before because it would have been assigned a default layer tag. 
    EdgeCrossingEdge:
        https://www.openstreetmap.org/way/118837631 has a layer tag of 1.
        https://www.openstreetmap.org/way/118837630 has no layer tag.
        These two ways cross, but are improperly flagged because they are on different layers. The layer comparison breaks because the second way (with no layer tag) is no longer assigned a default for the comparison.

**Comment by danielduhh** [comment]
@Bentleysb Is this still an issue ?

**Comment by Bentleysb** [comment]
Nope, closing.
