### ISSUE TITLE
Atlas TaggableFilter update causing "object not serializable" error

### ISSUE THREAD

**Issue by nachtm** [osmlab/atlas-checks#89]
It looks like the newest version of Atlas has a lambda function that is not serializable, which is causing a `NotSerializableException`. More specifically, when I run the project, I'm getting this error:
`Exception during serialization: java.io.NotSerializableException: org.openstreetmap.atlas.tags.filters.LineFilterConverter$$Lambda$67/1932303196`. 

It looks like it's fixed by [this PR](https://github.com/osmlab/atlas/pull/256). Once there's a new version of Atlas with the fix available, we should bump the version of this project as well.

**Comment by matthieun** [comment]
@nachtm Atlas 5.2.1 is out with the fix, will be in Maven Central soon!

**Comment by nachtm** [comment]
Thanks @matthieun! I can confirm that this is working for me now, thanks to #90.
